name: Alberto Gaitán
favicon: null
layout_spectrum: 0.11813323781825602
typography_spectrum: 0.5825069169513881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.13350868574343622
  lightness: 0.5923032271675766
  saturation: 0.1427090261131525
  rhythmicContrast: 0.7258204829413444
purpose: []
